### ISSUE TITLE
The word "application" is mistyped in some files, causing errors.

### ISSUE THREAD

**Issue by apaganuchi** [mehulthakkar1/Ajax.NET#1]
The word "application" in the content-type header configuration is mistyped in the files AjaxJavaScriptHandler.cs (at line 26) and AjaxEmbededJavaScriptHandler.cs (at line 25).

This causes problems depending on how IIS or firewalls are configured.

context.Response.AddHeader("Content-Type", "**applicatoin**/x-javascript");

**Comment by mehulthakkar1** [comment]
fixed Now :). Thank you for reporting.
